gallery/urls.py
from django.conf.urls import patterns, url

from gallery import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<folder_id>[0-9]+)/$', views.index, name='index'),
    url(r'^(?P<folder_id>[0-9]+)/(?P<image>[\w\.-]+)$', views.browse, name='browse'),
)

slimgallery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^gallery/', include('gallery.urls', namespace="gallery")),
    url(r'^admin/', include(admin.site.urls)),

)

gallery/models.py
from django.db import models

class Folder(models.Model):
    caption = models.CharField(max_length=40)
    parentfolder = models.ForeignKey("self", blank=True, null=True)
    folderpath = models.CharField(max_length=255)
    isAlbum = models.BooleanField(default=False)
    thumbSizeX = models.IntegerField(max_length=4, default=150)
    thumbSizeY = models.IntegerField(max_length=4, default=120)
    thumbQuality = models.IntegerField(max_length=3, default=80)
    picsPerRow = models.IntegerField(max_length=1, default=5)
    
    def __unicode__(self):
        return self.caption

gallery/views.py
# coding=UTF-8
from django.template import loader, Context
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from gallery.models import Folder
from django.conf import settings
from os import listdir, makedirs, system

def getPicturesFromFolder(folder, context):
    # generate path to the top folder
    current = folder
    root_path = ""
    while current.parentfolder is not None:
        root_path = current.parentfolder.folderpath + "/" + root_path
        current = current.parentfolder
    # put paths together
    picfolder_path = settings.SG_UPLOAD_PATH + root_path + folder.folderpath + "/"
    thumbfolder_path = settings.SG_THUMBS_PATH + root_path + folder.folderpath + "/"
    # path strings for templates
    html_picfolder_path = "user/" + root_path + folder.folderpath + "/"
    html_thumbfolder_path = "thumbs/" + root_path + folder.folderpath + "/"
    context['picfolder_path'] = html_picfolder_path
    context['thumbfolder_path'] = html_thumbfolder_path
    # get piclist and thumblist
    try:
        piclist = listdir(picfolder_path)
        piclist.sort()
        context['piclist'] = piclist
    except (IOError, OSError):
        return False, "Path %s not found." % (picfolder_path)
    try:
        thumblist = listdir(thumbfolder_path)
        thumblist.sort()
        # compare pics and thumbs and check if we need to create thumbs
        if len(piclist) != len(thumblist):
            for pic in piclist:
                for thumb in thumblist:
                    if pic in thumb:
                        break
                    else:
                        # no thumb for this pic found in thumblist
                        if thumblist.index(thumb) == (len(thumblist) - 1):
                            # create thumb
                            picpath = picfolder_path + pic
                            thumbpath = thumbfolder_path + "thumb_" + pic
                            retval = system("convert \"%s\" -resize %sx%s -quality %s \"%s\"" % (picpath, folder.thumbSizeX,
                                                                               folder.thumbSizeY,
                                                                               folder.thumbQuality, thumbpath))
                            if retval != 0:
                                return False, "Error while generating thumbnails."
        thumblist = listdir(thumbfolder_path)
        thumblist.sort()
        context['thumblist'] = thumblist
        return True, ""
    except (IOError, OSError):
        # no thumbfolder found for this picfolder => create it
        try:
            makedirs(thumbfolder_path)
        except (IOError, OSError):
            return False, "Error while creating thumbnail folder."
        for pic in piclist:
            # create thumbs for this picfolder
            picpath = picfolder_path + pic
            thumbpath = thumbfolder_path + "thumb_" + pic
            retval = system("convert \"%s\" -resize %sx%s -quality %s \"%s\"" % (picpath, folder.thumbSizeX,
                                                               folder.thumbSizeY,
                                                               folder.thumbQuality, thumbpath))
            if retval != 0:
                return False, "Error while generating thumbnails."
        thumblist = listdir(thumbfolder_path)
        thumblist.sort()
        context['thumblist'] = thumblist
        return True, ""

def index(request, folder_id=None):
    context = {}
    if folder_id is not None:
        folder = Folder.objects.get(id__exact=folder_id)
    if folder_id is not None and folder is not None:
        context['folder'] = folder
    if folder_id is not None and folder is not None and folder.isAlbum:
        # folder is valid and an album => get pic- and thumblist
        retval, errorstring = getPicturesFromFolder(folder, context)
        if not retval:
            return HttpResponseNotFound("%s" % (errorstring))
    else:
        # folder is not an album => get folderlist
        folder_list = Folder.objects.filter(parentfolder=folder_id)
        context['folder_list'] = folder_list
    return render(request, 'gallery/index.html', context)

def browse(request, folder_id=None, image=None):
    context = {}
    if folder_id is not None:
        folder = Folder.objects.get(id__exact=folder_id)
        if folder is not None and folder.isAlbum:
            # render a page with a single image in full size
            context['folder'] = folder
            retval, errorstring = getPicturesFromFolder(folder, context)
            if not retval:
                return HttpResponseNotFound("%s" % (errorstring))
            if not image in context['piclist']:
                return HttpResponseNotFound("Image not found in folder.")
            context['image'] = image
            # store names of the first and last image to jump to the beginning and the end:
            context['first'] = context['piclist'][0]
            context['last'] = context['piclist'][-1]
            # store names of the previous and next image to jump forth and back:
            if context['piclist'].index(image) != 0:
                context['previous'] = context['piclist'][context['piclist'].index(image) - 1]
            else:
                context['previous'] = context['piclist'][0]
            if context['piclist'][-1] != image:
                context['next'] = context['piclist'][context['piclist'].index(image) + 1]
            else:
                context['next'] = context['piclist'][-1]
            return render(request, 'gallery/browse.html', context)
        else:
            return HttpResponseNotFound("Folder does not exist or is not an album.")
    else:
        return HttpResponseNotFound("No folder given.")

gallery/templates/gallery/browse.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}

	{% if folder and folder.isAlbum and image %}
	
	<h4 class="title">{% if folder %}{{ folder.caption }}{% else %}Slimgallery{% endif %}</h4>

	<div align="center">

		<img src="{% static picfolder_path|add:image %}" alt="{{ image }}" width="800"/>
		<p>{{ image }}</p>

		<p>
			<a href="{% url 'gallery:browse' folder.id first %}"><img class="ico" src="{% static "gallery/first.png" %}" alt="first.png"/></a>
			<a href="{% url 'gallery:browse' folder.id previous %}"><img class="ico" src="{% static "gallery/previous.png" %}" alt="previous.png"/></a>
			<a href="{% url 'gallery:index' folder.id %}"><img class="ico" src="{% static "gallery/up.png" %}" alt="up.png"/></a>
			<a href="{% url 'gallery:browse' folder.id next %}"><img class="ico" src="{% static "gallery/next.png" %}" alt="next.png"/></a>
			<a href="{% url 'gallery:browse' folder.id last %}"><img class="ico" src="{% static "gallery/last.png" %}" alt="last.png"/></a>
		</p>
		
	</div>

	{% endif %}

{% endblock %}

gallery/templates/gallery/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}

	<h4 class="title">{% if folder %}{{ folder.caption }}{% else %}Slimgallery{% endif %}</h4>

	{% if folder and folder.isAlbum %}

		{% if thumblist %}

			<table align="center">

				<tr>

					{% for pic in piclist %}

						<td><a href="{% url 'gallery:browse' folder.id pic %}">
							<img src="{% static thumbfolder_path|add:"thumb_"|add:pic %}" alt="{{ pic }}"/></a>
							<p><a href="{% url 'gallery:browse' folder.id pic %}">{{ pic }}</a></p>
						</td>
						
						{% if forloop.counter|divisibleby:folder.picsPerRow and not forloop.last %}</tr>
						<tr>
						{% endif %}

					{% endfor %}

				</tr>


			</table>

		{% endif %}

	{% else %}
	
		{% if folder_list %}

			<table align="center" cellpadding="20">

				<tr>

					{% for folder in folder_list %}

						<td><a href="{% url 'gallery:index' folder.id %}">
							<img src="{% static "gallery/folder.png" %}" alt="folder.png"/></a>
							<p><a href="{% url 'gallery:index' folder.id %}">{{ folder.caption }}</a></p>
						</td>

					{% endfor %}

				</tr>


			</table>

		{% endif %}
		
	{% endif %}
	
	{% if folder %}
		{% if folder.parentfolder %}
			<p align="center"><a href="{% url 'gallery:index' folder.parentfolder.id %}"><img class="ico" src="{% static "gallery/up.png" %}" alt="up.png"/></a></p>
		{% else %}
			<p align="center"><a href="{% url 'gallery:index' %}"><img class="ico" src="{% static "gallery/up.png" %}" alt="up.png"/></a></p>
		{% endif %}
	{% endif %}

{% endblock %}

slimgallery/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html lang="en-EN">

<head>
	<title>Slimgallery</title>
	<meta name="description" content="Slimgallery picture gallery">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<style type="text/css"><!--

* {
 font-family: Arial,Helvetica,sans-serif;
 color:#888;
}

.title {
 text-align:center;
 margin-top:30px;
}

table {
 border-collapse:collapse;
 empty-cells:show;
 text-align:center;
 /*font-size:small;*/
 font-size:x-small;
}

td {
 border-style:solid;
 border-width:0px;
 padding-left:20px;
 padding-right:20px;
 padding-top:20px;
 padding-bottom:0px;
}

img.ico {
 width:32px;
 height:32px;
}

//--></style>

</head>

<body>

	{% block content %}{% endblock %}
	
	<p align="center" style="font-size:small;">Powered by <a href="https://github.com/okraits/slimgallery" target=_blank>slimgallery</a></p>

</body>	

</html>